### ISSUE TITLE
Enterprise Seats Usage shows as 0 in docker deployment

### ISSUE THREAD

**Issue by acheremisov** [github-copilot-resources/copilot-metrics-viewer#88]
Using latest Docker image (latest, 1.7) shows 0 seat usage
Tried to cURL directly all data is there

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/enterprises/ENTERPRISE_NAME/copilot/billing/seats
```

![Screenshot](https://github.com/user-attachments/assets/f8fe73a2-1ea5-4b4d-b8a9-6f7934670f4c)

**Comment by muminkoykiran** [comment]
Why limit existing features of the app instead of developing it further?

<img width="947" alt="image" src="https://github.com/user-attachments/assets/17b0d7bd-78ce-4f78-af5c-cb011b39cefd">

https://github.com/github-copilot-resources/copilot-metrics-viewer/blob/main/src/api/ExtractSeats.ts#L16-L18

It is intentional to disable this feature due to the addition of the sections I mentioned above. I can still access the seat list of the enterprise account with the API.

**Comment by martedesco** [comment]
It is not intentional :) It was just not updated yet as the Enterprise seats API came later! I will take a look at it later this week and raise a PR for it, if nobody does it sooner.

**Comment by dcieslak19973** [comment]
I think I addressed that here: https://github.com/github-copilot-resources/copilot-metrics-viewer/pull/76

**Comment by martedesco** [comment]
Thanks for the contribution @dcieslak19973 ! PR Merged 🎉
